# -*- coding: utf-8 -*-
"""GiftRecomm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmeNgkJt4JNjK5pSWhZKkYKdKpQDYsoi
"""

import pandas as pd
import numpy as np
import sklearn
import warnings
warnings.filterwarnings("ignore")

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('data (1).csv')
df.head(2)

df.columns

df.isnull().sum()

df.info()

X = df[['Gender','Age','Food','allowance/salary','studied','intr-extrovert','music genre','movie genre' ]].values
y= df['Gift'].values

from sklearn.linear_model import LogisticRegression

#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

model = LogisticRegression(solver='liblinear')
#model.fit(X_train,y_train)
model.fit(X,y)

print("prediction for datapoint 0:", model.predict([X[0]]))
#print(model.score(X, y) * 100)

#!pip install flask-ngrok

from flask_ngrok import run_with_ngrok
from flask import Flask,jsonify

app =Flask(__name__)
run_with_ngrok(app) #starts ngrok when the app is running
@app.route("/<int:Gender>/<int:Age>/<int:Food>/<int:sal>/<int:studied>/<int:inexovert>/<int:musgen>/<int:movgen>")
def home(Gender,Age,Food,sal,studied,inexovert,musgen,movgen):
  p = []
  p += [Gender,Age,Food,sal,studied,inexovert,musgen,movgen]
  
  arr = np.array([p])
  predict =model.predict(arr)
  print(predict)
 
  labelencoding = {"0":"Makeup/SunGlasses","1":"jewelry(Male/FeMale)/Watch/Ring/Perfume",
                   "2":"Flowers",
                   "3":"Books/Novel/Cooking-Books/photo-Album",
                   "4":"IT-Gadget/Laptop/Mobile/Airpods/DSLR",
                   "5":"Video-Games/Playstation/joystick/Gamebox",
                   "6":"Bike/Car/Bycycle",
                   "7":"Movi-Tickets/tours",
                   "8":"Bags/tour-bags",
                   "9":"Skateboard/skate-shoes/Football",
                   "10":"Food/Pizza",
                   "11":"Toys/Dolls",
                   "12":"Shoping",
                   "13":"Guitar",
                   "14":"Clothes/Shirts/Pents"}
  print(predict.item(0))
  result =labelencoding.get(str(predict.item(0)))
  print(result)
  return jsonify(result)
app.run()